theme: minima #jekyll-theme-architect
title: "Notes for Web Development"
author: "Weinian He"
description: "Notes for development, test, deploy, fixes."
show_excerpts: true # set to false to remove excerpts on the homepage
